# fly.toml app configuration file generated for apar-monitoring-system-api on 2024-04-08T15:18:54+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'apar-monitoring-system-api'
primary_region = 'sin'

[build]

[deploy]
  release_command = 'npm run db-setup'

[env]
DATABASE_ENVIRONMENT = "production"
PORT = "8083"

[http_service]
  internal_port = 8083
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
