# fly.toml app configuration file generated for apar-monitoring-system-api-apps on 2024-02-11T13:55:09+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'apar-monitoring-system-api-apps'
primary_region = 'sin'

[build]

[deploy]
  release_command = 'npm run db-setup'

[[mounts]]
  source = 'data'
  destination = '/data'

[env]
DATABASE_ENVIRONMENT = "production"
PORT = "8082"

[http_service]
  internal_port = 8082
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
